#!/usr/bin/env npx ts-node
/**
 * Migration Script: Convert documents_vec from blob storage to vec0 virtual table
 * 
 * This script:
 * 1. Backs up the current database
 * 2. Drops the blob-based documents_vec table
 * 3. Creates a vec0 virtual table for native vector operations
 * 4. (Embeddings must be regenerated by running `npm run index`)
 * 
 * Usage:
 *   npx ts-node scripts/migrate-vec-to-vec0.ts [--db-path <path>]
 * 
 * After running, regenerate embeddings with:
 *   npm run index
 */

import Database from 'better-sqlite3';
import * as fs from 'fs';
import * as path from 'path';

// Parse arguments
const args = process.argv.slice(2);
let dbPath = path.join(process.cwd(), 'data', 'tribal-knowledge.db');

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--db-path' && args[i + 1]) {
    dbPath = args[i + 1];
    i++;
  }
}

console.log('='.repeat(60));
console.log('documents_vec Migration: blob → vec0');
console.log('='.repeat(60));
console.log(`Database: ${dbPath}\n`);

// Check if database exists
if (!fs.existsSync(dbPath)) {
  console.error(`❌ Database not found: ${dbPath}`);
  process.exit(1);
}

// Open database
const db = new Database(dbPath);

// Check current schema
const currentSchema = db.prepare(`
  SELECT sql FROM sqlite_master 
  WHERE type='table' AND name='documents_vec'
`).get() as { sql: string } | undefined;

if (!currentSchema) {
  console.error('❌ documents_vec table not found');
  db.close();
  process.exit(1);
}

console.log('Current schema:');
console.log(currentSchema.sql);
console.log();

// Check if already vec0
if (currentSchema.sql.toLowerCase().includes('virtual table') || 
    currentSchema.sql.toLowerCase().includes('vec0')) {
  console.log('✅ documents_vec is already using vec0 virtual table');
  db.close();
  process.exit(0);
}

// Try to load sqlite-vec extension
const extensionPaths = [
  path.join(process.cwd(), 'node_modules', 'sqlite-vec-darwin-arm64', 'vec0'),
  path.join(process.cwd(), 'node_modules', 'sqlite-vec-darwin-x64', 'vec0'),
  path.join(process.cwd(), 'node_modules', 'sqlite-vec-linux-x64', 'vec0'),
  path.join(process.cwd(), 'node_modules', 'sqlite-vec', 'dist', 'vec0'),
  path.join(process.cwd(), 'sqlite-vec', 'dist', 'vec0'),
  '/usr/local/lib/sqlite-vec/vec0',
];

let vecLoaded = false;
for (const extPath of extensionPaths) {
  try {
    db.loadExtension(extPath);
    console.log(`✅ Loaded sqlite-vec from: ${extPath}`);
    vecLoaded = true;
    break;
  } catch {
    // Try next path
  }
}

if (!vecLoaded) {
  console.error('❌ Could not load sqlite-vec extension');
  console.error('Tried paths:', extensionPaths);
  db.close();
  process.exit(1);
}

// Create backup
const backupPath = dbPath.replace('.db', `-backup-${Date.now()}.db`);
console.log(`\n📦 Creating backup: ${backupPath}`);
fs.copyFileSync(dbPath, backupPath);
console.log('✅ Backup created');

// Get current embedding count
const embeddingCount = db.prepare('SELECT COUNT(*) as count FROM documents_vec').get() as { count: number };
console.log(`\n📊 Current embeddings: ${embeddingCount.count}`);

// Perform migration
console.log('\n🔄 Migrating documents_vec...');

try {
  db.exec('BEGIN TRANSACTION');
  
  // Drop the blob-based table
  db.exec('DROP TABLE IF EXISTS documents_vec');
  console.log('  - Dropped blob-based table');
  
  // Create vec0 virtual table with document_id (matches expected schema)
  db.exec(`
    CREATE VIRTUAL TABLE documents_vec USING vec0(
      document_id INTEGER PRIMARY KEY,
      embedding float[1536]
    )
  `);
  console.log('  - Created vec0 virtual table with document_id column');
  
  db.exec('COMMIT');
  console.log('\n✅ Migration complete!');
  
} catch (error) {
  db.exec('ROLLBACK');
  console.error('\n❌ Migration failed:', error);
  console.log(`Restore from backup: ${backupPath}`);
  db.close();
  process.exit(1);
}

// Verify new schema
const newSchema = db.prepare(`
  SELECT sql FROM sqlite_master 
  WHERE type='table' AND name='documents_vec'
`).get() as { sql: string } | undefined;

console.log('\nNew schema:');
console.log(newSchema?.sql || '(virtual table - check sqlite_master for type=table)');

// Check vec0 auxiliary tables
const vecTables = db.prepare(`
  SELECT name FROM sqlite_master 
  WHERE type='table' AND name LIKE 'documents_vec%'
`).all() as { name: string }[];

console.log('\nvec0 tables created:');
vecTables.forEach(t => console.log(`  - ${t.name}`));

db.close();

console.log('\n' + '='.repeat(60));
console.log('⚠️  IMPORTANT: Embeddings have been cleared!');
console.log('');
console.log('To regenerate embeddings, run:');
console.log('  npm run index');
console.log('');
console.log('Or for a full re-index:');
console.log('  npm run index:fresh');
console.log('='.repeat(60));
